### ISSUE TITLE
Unable to launch a jnlp file

### ISSUE THREAD

**Issue by jsa34** [Axway/ats-framework#45]
Issue: When trying to start a JNLP file (launching), I come across the following issue:
```

javax.jnlp.UnavailableServiceException: uninitialized
	at javax.jnlp.ServiceManager.lookup(Unknown Source)
	at oracle.apps.fnd.formsClient.jnlp.FndFormsEngine.<init>(FndFormsEngine.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at netx.jnlp.Launcher.createApplet(Launcher.java:376)
	at netx.jnlp.Launcher.launchApplet(Launcher.java:337)
	at netx.jnlp.Launcher$TgThread.run(Launcher.java:468)
```

The JNLP is of type Oracle Forms: https://oracle-base.com/articles/11g/oracle-forms-11g-and-java-web-start
The JNLP file retrieved as a local file using: 

SwingDriver.getSwingDriver("file:///C:/Users/Jason/Downloads/frmservlet", true);

**Comment by svilen-d** [comment]
Hello jsa34,

There are several exceptions pasted but most probably the cause is that you search for frame with title _Oracle Forms_:
> Caused by: com.axway.ats.uiengine.exceptions.ElementNotFoundException: Unable to find frame with title 'Oracle Forms'
  whereas later in the printed elements hierarchy it seems to be named differently (with '- Applet' at the end ):
> Component hierarchy:
   java.awt.Frame[name='frame0', title='Oracle Forms - Applet',

Note that ATS is using FEST-Swing library (org.fest.swing package, https://github.com/alexruiz/fest-swing-1.x) which is not recently updated. Also we have not tested with with applets so it might not be compatible.

Hope that helps!

**Comment by jsa34** [comment]
Yes - I could see this, however I have not set the expected window title - it seems to be self-derived when instantiating the SwingDriver

**Comment by svilen-d** [comment]
The windows title searched comes from the **title** defined in the JNLP file. 
For more technical details you may check the source of com.axway.ats.uiengine.SwingDriver.start() method for example. There ATS uses netx-hunson library to parse and start the app defined in the JNLP file.

**Comment by jsa34** [comment]
Ah - Apologies, I really should have looked at the source... I was just going by the possible constructors, and it looks like it's just missing a constructor for setting the window title when setting the app type as JNLP.

I have done this by creating a custom class for instantiating the SwingDriver, but when I try and use the inspector, it returns: 

CustomSwingDriver cannot be cast to com.axway.ats.uiengine.internal.driver.SwingDriverInternal

**Comment by dslaveykov** [comment]
Hello,
could you provide a little bit more of the stack-trace.

**Comment by jsa34** [comment]
That's all I have:

```
java.lang.ClassCastException: com.test.driver.CustomSwingDriver cannot be cast to com.axway.ats.uiengine.internal.driver.SwingDriverInternal
	at com.axway.ats.uiengine.engine.SwingEngine.useComponentInspector(SwingEngine.java:570)
	at com.test.DriverManager.createJavaDriver(DriverManager.java:96)
```

Custom constructor used:

```
package com.test.driver;

import com.axway.ats.uiengine.SwingDriver;

public class CustomSwingDriver extends SwingDriver {
    public CustomSwingDriver(String jnlpLocation, String windowTitle, boolean cacheEnabled) {
        super(jnlpLocation, cacheEnabled);
        this.windowTitle = windowTitle;
    }
}
```

**Comment by jsa34** [comment]
I've raised a PR for the SwingDriver constructors that should resolve this
